# NCI WeatherBench-3b: Train a CNN

In this notebook we will go through all the steps required to train a fully convolutional neural network. Because this takes a while and uses a lot of GPU RAM a separate command line script (`train_nn.py`) is also provided in the `src` directory.

In [1]:
%load_ext autoreload
%autoreload 2
import warnings
import os
warnings.filterwarnings('ignore')
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"
from score import *
import numpy as np
import xarray as xr
import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras.layers import Input, Dropout, Conv2D, Lambda, LeakyReLU
from tensorflow.python.client import device_lib
from dask.diagnostics import ProgressBar
from datetime import datetime
import train_nn
print (f"\nTF Device: {tf.config.list_physical_devices('GPU')}" )
train_nn.limit_mem()
from dask.distributed import Client

2024-03-23 17:47:14.960815: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.



TF Device: []


2024-03-23 17:47:17.495807: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [2]:
client = Client(n_workers=12, threads_per_worker=1)  
client

/opt/conda/envs/mlenv/lib/python3.9/site-packages/dask/config.py:742: FutureWarning: Dask configuration key 'distributed.scheduler.transition-log-length' has been deprecated; please use 'distributed.admin.low-level-log-length' instead
  warnings.warn(
/opt/conda/envs/mlenv/lib/python3.9/site-packages/dask/config.py:742: FutureWarning: Dask configuration key 'distributed.scheduler.events-log-length' has been deprecated; please use 'distributed.admin.low-level-log-length' instead
  warnings.warn(
/opt/conda/envs/mlenv/lib/python3.9/site-packages/dask/config.py:742: FutureWarning: Dask configuration key 'distributed.comm.recent-messages-log-length' has been deprecated; please use 'distributed.admin.low-level-log-length' instead
  warnings.warn(
/opt/conda/envs/mlenv/lib/python3.9/site-packages/dask/config.py:742: FutureWarning: Dask configuration key 'distributed.scheduler.transition-log-length' has been deprecated; please use 'distributed.admin.low-level-log-length' instead
  warnings.wa

<Client: 'tcp://127.0.0.1:38899' processes=12 threads=12, memory=95.00 GiB>

# Dataset: '5.625'

In [3]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )

res     = '5.625'
datadir = f'/g/data/wb00/NCI-Weatherbench/{res}deg' 
print ("Data loading..." )

years = list(range(1999, 2022+1))
print (years)
z_files = [ file for year in years for file in glob.glob (fr'{datadir}/geopotential/*{year}*')  ] 
t_files = [ file for year in years for file in glob.glob (fr'{datadir}/temperature/*{year}*')    ] 

z = xr.open_mfdataset(z_files, combine='by_coords', parallel=True, chunks={'time': 10}).z.sel(level=[500]).load() 
t = xr.open_mfdataset(t_files, combine='by_coords', parallel=True, chunks={'time': 10}).t.sel(level=[850]).drop('level').load() 
datasets = [z, t]
print ("Merging ... ")
ds = xr.merge(datasets).compute()  

[2024-03-22 23:09:46]
Data loading...
[1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
Merging ... 
CPU times: user 46.4 s, sys: 6.14 s, total: 52.5 s
Wall time: 56.1 s


In [4]:
z['time'][:10]

<xarray.DataArray 'time' (time: 10)>
array(['1999-01-01T00:00:00.000000000', '1999-01-01T01:00:00.000000000',
       '1999-01-01T02:00:00.000000000', '1999-01-01T03:00:00.000000000',
       '1999-01-01T04:00:00.000000000', '1999-01-01T05:00:00.000000000',
       '1999-01-01T06:00:00.000000000', '1999-01-01T07:00:00.000000000',
       '1999-01-01T08:00:00.000000000', '1999-01-01T09:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1999-01-01 ... 1999-01-01T09:00:00

In [5]:
z['time'][-10:]

<xarray.DataArray 'time' (time: 10)>
array(['2022-12-31T14:00:00.000000000', '2022-12-31T15:00:00.000000000',
       '2022-12-31T16:00:00.000000000', '2022-12-31T17:00:00.000000000',
       '2022-12-31T18:00:00.000000000', '2022-12-31T19:00:00.000000000',
       '2022-12-31T20:00:00.000000000', '2022-12-31T21:00:00.000000000',
       '2022-12-31T22:00:00.000000000', '2022-12-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2022-12-31T14:00:00 ... 2022-12-31T23:00:00

In [6]:
def data_generate(ds, lead_time):
    ds_train = ds.sel(time=slice(*train_years))
    ds_valid = ds.sel(time=slice(*valid_years))
    ds_test  = ds.sel(time=slice(*test_years))

    print ("Data generation ... ")
    dic = {var: 500 for var in vars}
    dg_train = train_nn.DataGenerator(ds_train, dic, lead_time, batch_size=batch_size)
    dg_valid = train_nn.DataGenerator(ds_valid, dic, lead_time, batch_size=batch_size, mean=dg_train.mean,
                         std=dg_train.std, shuffle=False)
    dg_test =  train_nn.DataGenerator(ds_test, dic, lead_time, batch_size=batch_size, mean=dg_train.mean,
                         std=dg_train.std, shuffle=False)

    print(f'Mean = {dg_train.mean}; Std = {dg_train.std}')
    return dg_train, dg_valid, dg_test

def train(dg_train, dg_valid, dg_test, model_save_fn):
    print ("Train model ... ") 
    model = train_nn.build_cnn(filters, kernels, input_shape=(32, 64, len(vars)), dr=dr)    
    model.compile(keras.optimizers.Adam(lr), 'mse')
    print(model.summary())
    
    model.fit(dg_train, epochs=100, validation_data=dg_valid,
                          callbacks=[tf.keras.callbacks.EarlyStopping(
                          monitor='val_loss',
                          min_delta=0,
                          patience=patience,
                          verbose=1,
                          mode='auto'
                      )]
                      )
    print(f'Saving model weights: {model_save_fn}')
    model.save_weights(model_save_fn)   
    return model

def prediction(model, dg_test, iterative, iterative_lead_time, pred_save_fn):    
    print("Create predictions ...")
    pred = train_nn.create_iterative_predictions(model, dg_test, iterative_lead_time) if iterative \
                                                        else train_nn.create_predictions(model, dg_test)
    print(f'Saving predictions: {pred_save_fn}')
    pred.to_netcdf(pred_save_fn)
    return pred
    
def evaluate(pred, iterative, test_years):     
    print("Evaluating forecast ...")
    valid_years = list( range(int(test_years[0]), int(test_years[1])+1 ))
    print ('all test_years:', valid_years)
    z500_valid_files = [ file for year in valid_years for file in glob.glob (fr'{datadir}/geopotential/*{year}*') ] 
    t850_valid_files = [ file for year in valid_years for file in glob.glob (fr'{datadir}/temperature/*{year}*')  ]     

    z500_valid = train_nn.load_test_data(z500_valid_files, 'z', slice(*test_years)) 
    t850_valid = train_nn.load_test_data(t850_valid_files, 't', slice(*test_years))     
    valid      = xr.merge([z500_valid, t850_valid], compat='override').compute()
    
    print(train_nn.evaluate_iterative_forecast(pred, valid, compute_weighted_rmse).load() if iterative \
                                                else train_nn.compute_weighted_rmse(pred, valid).compute())

def reset():
    print("Resetting ...")
    import IPython
    IPython.Application.instance().kernel.do_shutdown(True)
    IPython.Application.instance().kernel.do_shutdown(True)


In [7]:
test_years =('2021', '2022')
test_years = list (range(int (test_years[0]), int(test_years[1])+1 ))
print ('test_years:', test_years)

test_years: [2021, 2022]


# 72 hours (3 days)

In [8]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )
print (60*"-")
train_years=('1999', '2015')
valid_years=('2016', '2020')
test_years =('2021', '2022')
batch_size = 32
vars = ('z', 't')
lead_time = 72
filters = [64, 64, 64, 64, 2]
kernels = [5, 5, 5, 5, 5]
dr = 0
patience = 3
save_prefix = 'NCI_tutorial' 
print ('save_prefix:', save_prefix)
model_save_fn = f'/scratch/vp91/mah900/NCI-Weatherbench/pred_dir/saved_models/{save_prefix}_cnn_3d.h5'
pred_save_fn  = f'/scratch/vp91/mah900/NCI-Weatherbench/pred_dir/{save_prefix}_cnn_3d.nc'
lr = 1e-4
iterative = False
iterative_lead_time = None

[2024-03-22 23:10:42]
------------------------------------------------------------
save_prefix: NCI_tutorial
CPU times: user 0 ns, sys: 72 µs, total: 72 µs
Wall time: 63.2 µs


In [9]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )
dg_train, dg_valid, dg_test = data_generate(ds, lead_time)
model = train(dg_train, dg_valid, dg_test, model_save_fn)

[2024-03-22 23:10:42]
Data generation ... 
Loading data into RAM
Loading data into RAM
Loading data into RAM
Mean = <xarray.DataArray 'z' (level: 2)>
array([54140.027  ,   274.65103], dtype=float32)
Coordinates:
  * level    (level) int32 500 500; Std = <xarray.DataArray 'z' (level: 2)>
array([1100.1848  ,    5.642098], dtype=float32)
Coordinates:
  * level    (level) int32 500 500
Train model ... 
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 32, 64, 2)]       0         
                                                                 
 periodic_conv2d (PeriodicC  (None, 32, 64, 64)        3264      
 onv2D)                                                          
                                                                 
 tf.nn.elu (TFOpLambda)      (None, 32, 64, 64)        0         
                                                       

2024-03-22 23:10:59.794481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 31141 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b1:00.0, compute capability: 7.0


                                                                 
Total params: 313858 (1.20 MB)
Trainable params: 313858 (1.20 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/100


2024-03-22 23:11:01.292432: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8800
2024-03-22 23:11:01.716928: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f0b09b90d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-03-22 23:11:01.716943: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-32GB, Compute Capability 7.0
2024-03-22 23:11:01.721274: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-03-22 23:11:01.854441: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


4655/4655 [==============================] - 73s 15ms/step - loss: 0.5054 - val_loss: 0.4787
Epoch 2/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.4543 - val_loss: 0.4548
Epoch 3/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.4370 - val_loss: 0.4419
Epoch 4/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.4252 - val_loss: 0.4301
Epoch 5/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.4167 - val_loss: 0.4309
Epoch 6/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.4095 - val_loss: 0.4224
Epoch 7/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.4038 - val_loss: 0.4242
Epoch 8/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.3987 - val_loss: 0.4166
Epoch 9/100
4655/4655 [==============================] - 70s 15ms/step - loss: 0.3943 - val_loss: 0.4129
Epoch 10/100
4655/4655 [==============================] - 70s 15ms/

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [10]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )
pred = prediction(model, dg_test, iterative, iterative_lead_time, pred_save_fn) 
evaluate(pred, iterative, test_years)

[2024-03-22 23:33:13]
Create predictions ...
Saving predictions: /scratch/vp91/mah900/NCI-Weatherbench/pred_dir/NCI_tutorial_cnn_3d.nc
Evaluating forecast ...
all test_years: [2021, 2022]
load_test_data, var: z
load_test_data, var: t
<xarray.Dataset>
Dimensions:  ()
Data variables:
    z        float64 637.0
    t        float64 2.938
CPU times: user 13 s, sys: 2.94 s, total: 15.9 s
Wall time: 12.9 s


# 120 hours (5 days)

In [11]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )

print (60*"-")
batch_size = 32
vars = ('z', 't')
lead_time = 120
filters = [64, 64, 64, 64, 2]
kernels = [5, 5, 5, 5, 5]
dr = 0
patience = 3
save_prefix = 'NCI_tutorial' 
print ('save_prefix:', save_prefix)
model_save_fn= f'/scratch/vp91/mah900/NCI-Weatherbench/pred_dir/saved_models/{save_prefix}_cnn_5d.h5'
pred_save_fn = f'/scratch/vp91/mah900/NCI-Weatherbench/pred_dir/{save_prefix}_cnn_5d.nc'
lr = 1e-4
iterative = False
iterative_lead_time = None

[2024-03-22 23:33:26]
------------------------------------------------------------
save_prefix: NCI_tutorial
CPU times: user 52 µs, sys: 15 µs, total: 67 µs
Wall time: 66 µs


In [12]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )
dg_train, dg_valid, dg_test =  data_generate(ds, lead_time)
model = train(dg_train, dg_valid, dg_test, model_save_fn)

[2024-03-22 23:33:26]
Data generation ... 
Loading data into RAM
Loading data into RAM
Loading data into RAM
Mean = <xarray.DataArray 'z' (level: 2)>
array([54140.027  ,   274.65103], dtype=float32)
Coordinates:
  * level    (level) int32 500 500; Std = <xarray.DataArray 'z' (level: 2)>
array([1100.1848  ,    5.642098], dtype=float32)
Coordinates:
  * level    (level) int32 500 500
Train model ... 
Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 32, 64, 2)]       0         
                                                                 
 periodic_conv2d_5 (Periodi  (None, 32, 64, 64)        3264      
 cConv2D)                                                        
                                                                 
 tf.nn.elu_4 (TFOpLambda)    (None, 32, 64, 64)        0         
                                                     

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



4653/4653 [==============================] - 70s 15ms/step - loss: 0.5632 - val_loss: 0.5748
Epoch 5/100
4653/4653 [==============================] - 70s 15ms/step - loss: 0.5555 - val_loss: 0.5741
Epoch 6/100
4653/4653 [==============================] - 70s 15ms/step - loss: 0.5491 - val_loss: 0.5720
Epoch 7/100
4653/4653 [==============================] - 70s 15ms/step - loss: 0.5433 - val_loss: 0.5692
Epoch 8/100
4653/4653 [==============================] - 70s 15ms/step - loss: 0.5381 - val_loss: 0.5700
Epoch 9/100
4653/4653 [==============================] - 70s 15ms/step - loss: 0.5330 - val_loss: 0.5709
Epoch 10/100
4245/4653 [==========================>...] - ETA: 5s - loss: 0.5284

KeyboardInterrupt: 

In [ ]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )
pred = prediction(model, dg_test, iterative, iterative_lead_time, pred_save_fn) 
evaluate(pred, iterative, test_years)

[2024-03-22 23:45:12]
Create predictions ...


Process Dask Worker process (from Nanny):
Process Dask Worker process (from Nanny):
distributed.nanny - ERROR - Worker process died unexpectedly
distributed.nanny - ERROR - Worker process died unexpectedly
Process Dask Worker process (from Nanny):
Process Dask Worker process (from Nanny):
Process Dask Worker process (from Nanny):
distributed.nanny - ERROR - Worker process died unexpectedly
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/envs/mlenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/mlenv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/mlenv/lib/python3.9/site-packages/distributed/process.py", line 202, in _run
    target(*args, **kwargs)
  File "/opt/conda/envs/mlenv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/

Saving predictions: /scratch/vp91/mah900/NCI-Weatherbench/pred_dir/NCI_tutorial_cnn_5d.nc
Evaluating forecast ...
all test_years: [2021, 2022]
load_test_data, var: z


# fccnn_6h_iter

In [ ]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )

print (60*"-")
batch_size = 32
vars = ('z', 't')
lead_time = 6
iterative_lead_time = 5 * 24 
filters = [64, 64, 64, 64, 2]
kernels = [5, 5, 5, 5, 5]
dr = 0
patience = 3
save_prefix = 'NCI_tutorial' 
print ('save_prefix:', save_prefix)
model_save_fn=f'/scratch/vp91/mah900/NCI-Weatherbench/pred_dir/saved_models/{save_prefix}_fccnn_6h_iter.h5'
pred_save_fn =f'/scratch/vp91/mah900/NCI-Weatherbench/pred_dir/{save_prefix}_fccnn_6h_iter.nc'
lr = 1e-4
iterative = True

In [ ]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )
dg_train, dg_valid, dg_test = data_generate(ds, lead_time)
model = train(dg_train, dg_valid, dg_test, model_save_fn)

In [ ]:
%%time
print( f'[{datetime.now().replace(microsecond=0)}]' )
pred = prediction(model, dg_test, iterative, iterative_lead_time, pred_save_fn)  
evaluate(pred, iterative, test_years)

In [ ]:
pred

In [ ]:
client.shutdown()